apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-nvmf-pvc-block
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: csi-nvmf-sc-block
  resources:
    requests:
      storage: 20Gi
      